/**
 * XOS Salesforce configuration. Keep every Salesforce API field and
 * organization-specific picklist value here so the adapter remains portable.
 */
const mapping = {
  apiVersion: 'v67.0',
  objects: {
    account: {
      name: 'Account',
      fields: {
        id: 'Id',
        name: 'Name',
        industry: 'Industry',
        employeeCount: 'Nombre_employes__c',
        customerType: 'Type_de_client__c',
        tier: 'Tier__c',
        parentId: 'ParentId',
        ownerId: 'OwnerId',
      },
      employeeBands: [
        '1 - 50',
        '51 - 250',
        '251 - 500',
        '501 - 1000',
        '1001 - 2000',
        '2001 - 4999',
        '5000 et plus',
      ],
      customerTypes: ['Client inactif', 'Client', 'Prospect'],
      tiers: ['A', 'B', 'C', 'D'],
      industries: [
        'Secteur public',
        'Aéronautique et Défense',
        'Biens de consommation alimentaires',
        'Communication et Médias',
        'Distribution spécialisée',
        'Divertissement',
        'E-Commerce, VAD',
        'Editeur de logiciels',
        'Education - Formation',
        'Entité à but non lucratif',
        'Environnement',
        'Grande distribution alimentaire',
        "Industrie de l'emballage",
        "Matériaux de construction et extraction d'autres matériaux (hors énergie)",
        'Messagerie, courrier',
        'Ordinateurs & Electronique grand public',
        'Portails, pure players Internet',
        'Relation Client',
        'Services aux entreprises ou aux collectivités',
        'Services de conseils',
        'Services informatiques',
        'Télévision, radio, cinéma',
        'Transports',
        'Publicité/Marketing/Relations publiques',
        'BTP / construction',
        'Chimie (fine et lourde) / plastique',
        'Agroalimentaire / agriculture',
        'Assurance / Réassurance / caisses de retraite',
        'Automobiles / équipementiers',
        'Banque / finance',
        'Construction mécanique / métallurgie / sidérurgie / machines-outils',
        'Culture & Loisirs',
        'Distribution BtoB',
        'Droguerie / parfumerie / hygiène / cosmétiques',
        'Energie',
        'Equipement de la maison / électroménager',
        'Equipement de la personne (vêtements, accessoires)',
        'Etablissements médicaux / centre de soins',
        'Immobilier / promotion immobilière',
        'Ingénierie / certifications et inspections techniques',
        'Luxe',
        'Matériels et composants électroniques / électriques / informatique',
        'Presse / édition / imprimerie',
        'Restauration collective / chaînes',
        'Santé / pharmacie / biotech',
        'Services à la personne / action sociale',
        'Services environnementaux / facility management',
        'Support, maintenance et logistique',
        'Télécommunications',
        'Tourisme / hôtellerie',
      ],
    },
    contact: {
      name: 'Contact',
      fields: {
        id: 'Id',
        name: 'Name',
        phone: 'Phone',
        accountId: 'AccountId',
        title: 'Title',
        linkedin: 'Profil_Linkedin__c',
        email: 'Email',
        mobilePhone: 'MobilePhone',
        decisionLevel: 'Niveau_de_d_cision__c',
        doNotCall: 'NPA__c',
        inactive: 'Inactif__c',
      },
      decisionLevels: ['+', '=', '-'],
      fonctionPresets: [
        {
          id: 'responsable_formation',
          label: 'Responsable formation',
          likes: ['%responsable%formation%'],
          exacts: ['RF'],
        },
        {
          id: 'directeur_formation',
          label: 'Directeur formation',
          likes: [
            '%direct%formation%',
            '%training director%',
            '%head of learning%',
          ],
          exacts: ['DF'],
        },
        {
          id: 'digital_learning_manager',
          label: 'Digital learning manager',
          likes: ['%digital learning%', '%e-learning%', '%elearning%'],
          exacts: ['DLM'],
        },
        {
          id: 'charge_formation',
          label: 'Chargé de formation',
          likes: [
            '%charg%formation%',
            '%chef de projet formation%',
            '%training manager%',
            '%learning manager%',
            '%training officer%',
            '%training coordinator%',
            '%gestionnaire%formation%',
            '%training project manager%',
            '%training specialist%',
            '%learning project manager%',
            '%coordinat%formation%',
            '%assistant%formation%',
          ],
          exacts: ['CF', 'CP'],
        },
        {
          id: 'responsable_rh',
          label: 'Responsable RH',
          likes: [
            '%responsable rh%',
            '%responsable ressources humaines%',
            '%responsable des ressources humaines%',
            '%responsable%service%ressources humaines%',
            '%hr manager%',
            '%human resources manager%',
            '%head of hr%',
            '%hr business partner%',
            '%human resources business partner%',
          ],
          exacts: ['RRH', 'HRBP', 'Cadre RH'],
        },
        {
          id: 'developpement_rh',
          label: 'Développement RH / compétences',
          likes: [
            '%développement rh%',
            '%developpement rh%',
            '%développement des ressources humaines%',
            '%developpement des ressources humaines%',
            '%développement des compétences%',
            '%developpement des competences%',
            '%développement humain%',
            '%hr development%',
            '%learning and development%',
            '%learning & development%',
          ],
          exacts: ['Développement RH'],
        },
        {
          id: 'directeur_rh',
          label: 'Directeur RH',
          likes: [
            '%drh%',
            '%directeur rh%',
            '%directrice rh%',
            '%directeur des ressources humaines%',
            '%directrice des ressources humaines%',
            '%direction des ressources humaines%',
            '%hr director%',
            '%human resources director%',
            '%chief human resources officer%',
            '%chief people officer%',
          ],
          exacts: ['CHRO'],
        },
        {
          id: 'pedagogie',
          label: 'Pédagogie / ingénierie pédagogique',
          likes: ['%pédagogique%', '%pedagogique%'],
          exacts: [],
        },
        {
          id: 'sirh',
          label: 'SIRH',
          likes: ['%sirh%'],
          exacts: [],
        },
        {
          id: 'recrutement',
          label: 'Recrutement',
          likes: ['%recrutement%', '%recruitment%'],
          exacts: [],
        },
        {
          id: 'direction_generale',
          label: 'Direction générale / dirigeant',
          likes: [
            '%directeur général%',
            '%directeur general%',
            '%pdg%',
            '%dirigeant%',
          ],
          exacts: [
            'CEO',
            'DG',
            'Président',
            'Présidente',
            'Gérant',
            'Gérante',
            'Chief Executive Officer',
          ],
        },
      ],
    },
    task: {
      name: 'Task',
      childRelationship: 'Tasks',
      fields: {
        id: 'Id',
        subject: 'Subject',
        description: 'Description',
        result: 'Resultat_call__c',
        subtype: 'TaskSubtype',
        duration: 'CallDurationInSeconds',
        whoId: 'WhoId',
        whatId: 'WhatId',
        status: 'Status',
        ownerId: 'OwnerId',
        activityDate: 'ActivityDate',
      },
      subtypeValue: 'Call',
      // Standard Task.Status API value (UI label may be "Achevée" in FR orgs).
      statusValue: 'Completed',
      results: [
        'Appel non décroché',
        'Message répondeur',
        'Appel décroché',
        'Appel argumenté',
        'RDV planifié',
      ],
      resultSemantic: {
        rdv: 'RDV planifié',
        followUpNoAnswer: 'Appel non décroché',
        followUpVoicemail: 'Message répondeur',
      },
    },
    opportunity: {
      name: 'Opportunity',
      fields: {
        id: 'Id',
        name: 'Name',
        accountId: 'AccountId',
        accountName: 'Account.Name',
        accountIndustry: 'Account.Industry',
        accountOwnerId: 'Account.OwnerId',
        accountOwnerName: 'Account.Owner.Name',
        isClosed: 'IsClosed',
        isWon: 'IsWon',
        stageName: 'StageName',
        amount: 'Amount',
        probability: 'Probability',
        expectedRevenue: 'ExpectedRevenue',
        closeDate: 'CloseDate',
        ownerId: 'OwnerId',
        ownerName: 'Owner.Name',
        ownerIsActive: 'Owner.IsActive',
        createdDate: 'CreatedDate',
        lastActivityDate: 'LastActivityDate',
        lastStageChangeDate: 'LastStageChangeDate',
      },
      saleTypeField: 'Type_de_vente__c',
      lossReasonField: 'Raison_de_perte_V2__c',
      describeMetadataKey: 'Opportunity',
      saleTypes: {
        catalogue: ['Catalogue'],
        sur_mesure: ['Sur-mesure'],
        conseil: ['Conseil'],
      },
      commissionTypeField: 'Type_de_commission__c',
      arrCommissionTypes: [
        'Abonnement 2 ans',
        'Abonnement 3 ans',
        'Abonnement 4 ans',
        'Abonnement 5 ans',
      ],
      closedLostStage: 'Fermée / Perdue',
    },
    opportunityHistory: {
      name: 'OpportunityHistory',
      fields: {
        opportunityId: 'OpportunityId',
        stageName: 'StageName',
        createdDate: 'CreatedDate',
        createdById: 'CreatedById',
      },
      stages: {
        proposalSent: 'Proposition envoyée',
        stalledSuspect: 'Suspect enlisé',
      },
      stageOrder: {
        'Projet identifié': 1,
        'XOS recommandé': 2,
        'Projet qualifié / AO reçu': 3,
        'Proposition envoyée': 4,
        'XOS short-listé': 5,
        'Nego technique engagée': 6,
        'Négo financière engagée': 7,
        'OK de principe': 8,
        'Fermée / Gagnée': 9,
        'Fermée / Perdue': 10,
        'Suspect enlisé': 11,
      },
    },
    event: {
      name: 'Event',
      relationName: 'EventRelation',
      fields: {
        subject: 'Subject',
        startDateTime: 'StartDateTime',
        endDateTime: 'EndDateTime',
        whoId: 'WhoId',
        whatId: 'WhatId',
        ownerId: 'OwnerId',
        relationId: 'RelationId',
        eventId: 'EventId',
        activityDate: 'ActivityDate',
      },
    },
    user: {
      name: 'User',
      fields: {
        id: 'Id',
        name: 'Name',
        email: 'Email',
        isActive: 'IsActive',
      },
    },
  },
};

export default mapping;
