create table if not exists public.recette_journal (
  id bigint generated by default as identity primary key,
  kind text not null,
  payload jsonb not null default '{}'::jsonb,
  actor_id uuid not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now()
);

create index if not exists recette_journal_actor_created_at_idx
  on public.recette_journal (actor_id, created_at desc);

alter table public.recette_journal enable row level security;

drop policy if exists "Authenticated users can read recette journal"
  on public.recette_journal;
create policy "Authenticated users can read recette journal"
  on public.recette_journal
  for select
  to authenticated
  using (true);

drop policy if exists "Service role can write recette journal"
  on public.recette_journal;
create policy "Service role can write recette journal"
  on public.recette_journal
  for insert
  to service_role
  with check (true);

grant select on public.recette_journal to authenticated;
grant select, insert on public.recette_journal to service_role;
grant usage, select on sequence public.recette_journal_id_seq to service_role;
